import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

//--------------------Route HAndlers -------------------

// rout-handlers allow you to handle custom request handlers for a given route. they are defined
// in a route.tsx or route.js file
// to avoid conflict between pager-route (page.tsx) and route-handler (route.tsx)
// place the rote-handler (route.ts) to a subdirectory named 'api'

//-------------------- POST request -------------------

// app/comments/route.ts
// https://www.youtube.com/watch?v=pzPS7Fn-8tE&list=PLC3y8-rFHvwjOKd6gdf4QtV1uYNiQnruI&index=35
// to test the request we can use VScode extension called 'Thunder Client'.

//-------------------- Dynamic Route Handler -------------------

// GET method
// see: app/comments/[id]/route.ts

//-------------------- Dynamic Route Handler -------------------

// PATCH method
// see: app/comments/[id]/route.ts
